services:
  # React client application
  app:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8081:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - mrp-network
      
  # PostgreSQL database for local development
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mrp_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mrp-network

networks:
  mrp-network:
    driver: bridge

volumes:
  postgres-data:
