// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xydntmjbpdzcyjdumnrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5ZG50bWpicGR6Y3lqZHVtbnJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NDM1NzAsImV4cCI6MjA2MDMxOTU3MH0.K88YsqVWQ4IwqrRaoXI1F6rjT9Ue_Ori7ShlzzRm3_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);